### ISSUE TITLE
Reverse-column class doesn't render properly on Safari

### ISSUE THREAD

**Issue by imgios** [lucaam/amorebirra#2]
As the title says, seems like Safari hates the reverse-column class. 

![Screen from an iPhone](https://user-images.githubusercontent.com/34242779/92090266-8266a680-edcf-11ea-9a30-8a426c5b7d21.jpg)

**Comment by lucaam** [comment]
This commit https://github.com/lucaam/amorebirra/commit/3107162a61884520ef1b8846beabaee004fe3a95 fixes this bug.
